### ISSUE TITLE
ArgumentError (unknown keyword: content_type)

### ISSUE THREAD

**Issue by mumuxizzz** [mycolorway/activestorage_qiniu#13]
使用[rails_admin](https://github.com/sferik/rails_admin)上传图片遇到错误

**环境**
ruby: 2.6.0
rails: 5.2.2

**出错堆栈信息**
```
ArgumentError (unknown keyword: content_type):
  
activestorage_qiniu (0.1.9) lib/active_storage/service/qiniu_service.rb:43:in `upload'
activestorage (5.2.2.rc1) app/models/active_storage/blob.rb:159:in `upload'
activestorage (5.2.2.rc1) app/models/active_storage/blob.rb:57:in `block in build_after_upload'
activestorage (5.2.2.rc1) app/models/active_storage/blob.rb:52:in `tap'
activestorage (5.2.2.rc1) app/models/active_storage/blob.rb:52:in `build_after_upload'
activestorage (5.2.2.rc1) app/models/active_storage/blob.rb:65:in `create_after_upload!'
activestorage (5.2.2.rc1) lib/active_storage/attached.rb:23:in `create_blob_from'
activestorage (5.2.2.rc1) lib/active_storage/attached/one.rb:24:in `attach'
activestorage (5.2.2.rc1) lib/active_storage/attached/macros.rb:37:in `bg='
activemodel (5.2.2.rc1) lib/active_model/attribute_assignment.rb:51:in `public_send'
activemodel (5.2.2.rc1) lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
activemodel (5.2.2.rc1) lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
activemodel (5.2.2.rc1) lib/active_model/attribute_assignment.rb:43:in `each'
activemodel (5.2.2.rc1) lib/active_model/attribute_assignment.rb:43:in `_assign_attributes'
activerecord (5.2.2.rc1) lib/active_record/attribute_assignment.rb:23:in `_assign_attributes'
activemodel (5.2.2.rc1) lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
rails_admin (1.4.2) lib/rails_admin/adapters/active_record/abstract_object.rb:19:in `set_attributes'
rails_admin (1.4.2) lib/rails_admin/config/actions/edit.rb:27:in `block (2 levels) in <class:Edit>'
rails_admin (1.4.2) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
rails_admin (1.4.2) app/controllers/rails_admin/main_controller.rb:22:in `edit'
actionpack (5.2.2.rc1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.2.rc1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.2.rc1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.2.rc1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.2.rc1) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.2.rc1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.2.rc1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.2.rc1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.2.rc1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.2.rc1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.2.rc1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.2.rc1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.2.rc1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.2.rc1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.2.rc1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.2.rc1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.2.rc1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.2.rc1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.2.rc1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.2.rc1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.2.rc1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.2.rc1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.2.rc1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.2.rc1) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.2.rc1) lib/rails/engine.rb:524:in `call'
railties (5.2.2.rc1) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.2.rc1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.2.rc1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.2.rc1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.2.rc1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.2.rc1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.2.rc1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.2.rc1) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'
remotipart (1.4.2) lib/remotipart/middleware.rb:32:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.2.rc1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.2.rc1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.2.rc1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.2.rc1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.2.rc1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.2.rc1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.2.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.2.rc1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2.rc1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2.rc1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2.rc1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2.rc1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2.rc1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2.rc1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.2.rc1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.2.rc1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2.rc1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2.rc1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
railties (5.2.2.rc1) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by mumuxizzz** [comment]
看到最新的提交已经修复了.
`gem 'activestorage_qiniu', github: 'mycolorway/activestorage_qiniu'`

**Comment by bastengao** [comment]
@mycolorway 可以 release 一个新版本吗？

**Comment by ichord** [comment]
已经打了 tag 了，要等 @seandong 发布到 ruby gems.
